services:
  study_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - MIX_ENV=prod
      - PHX_SERVER=true
      - PORT=4000
      - DATABASE_PATH=/app/data/study_bot.db
      - CHROMA_BASE_URL=http://localhost:8000
      - CHROMA_PERSIST_DIRECTORY=/app/chroma_data
    volumes:
      - ./data:/app/data
      - ./chroma_data:/app/chroma_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
