services:
  study_bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      chroma:
        condition: service_healthy
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - MIX_ENV=prod
      - PHX_SERVER=true
      - PORT=4000
      - DATABASE_PATH=/app/data/study_bot.db
      - CHROMA_BASE_URL=http://chroma:8000
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  chroma:
    build:
      context: .
      dockerfile: Dockerfile.chroma
    environment:
      - CHROMA_DB_IMPL=duckdb+parquet
      - CHROMA_PERSIST_DIRECTORY=/chroma_data
      - ALLOW_RESET=TRUE
    volumes:
      - ./chroma_data:/chroma_data
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/api/v2/heartbeat || curl -fsS http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
