version: '3.8'

services:
  study_bot:
    build: .
    ports:
      - "4000:4000"
    environment:
      - MIX_ENV=prod
      - PHX_SERVER=true
      - PORT=4000
      - DATABASE_PATH=/app/data/study_bot.db
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - PHX_HOST=${PHX_HOST:-localhost}
    volumes:
      - ./data:/app/data
      - ./chroma_data:/app/chroma_data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s